# Ejercicios del Guión de prácticas: Introducción breve a Tensores en Pytorch

**Asignatura**: Deep Learning para procesamiento de Lenguaje Natural, 2026/2027

**Profesor**: Juan A. Botía (juanbot@um.es)

**Máster de Inteligencia Artificial**

**Facultad de Informática**

![](https://www.um.es/image/layout_set_logo?img_id=175281&t=1726728636242)

**Universidad de Murcia**

![](https://www.um.es/o/um-lr-principal-um-home-theme/images/logo-um.png)

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>Ejercicio 1:Creación de Tensores</strong></div>

* Crea un tensor unidimensional con los valores [1, 2, 3, 4, 5].

* Crea un tensor bidimensional de tamaño (3, 3) lleno de números aleatorios.

* Crea un tensor de ceros con tamaño (4, 4).

* Imprime el tamaño, el tipo de datos y el dispositivo (CPU/GPU) de cada tensor.


In [12]:
import torch

# Tensor 1D
tensor_1d = torch.tensor([1, 2, 3, 4, 5])

# Tensor 2D con valores aleatorios
tensor_2d = torch.rand(3, 3)

# Tensor 4x4 de ceros
tensor_zeros = torch.zeros(4, 4)

# Imprimir propiedades
print("Tensor 1D:", tensor_1d)
print("Tamaño:", tensor_1d.shape)
print("Tipo de dato:", tensor_1d.dtype)
print("Dispositivo:", tensor_1d.device)

print("\nTensor 2D:", tensor_2d)
print("Tamaño:", tensor_2d.shape)
print("Tipo de dato:", tensor_2d.dtype)
print("Dispositivo:", tensor_2d.device)

print("\nTensor de ceros:", tensor_zeros)
print("Tamaño:", tensor_zeros.shape)
print("Tipo de dato:", tensor_zeros.dtype)
print("Dispositivo:", tensor_zeros.device)


Tensor 1D: tensor([1, 2, 3, 4, 5])
Tamaño: torch.Size([5])
Tipo de dato: torch.int64
Dispositivo: cpu

Tensor 2D: tensor([[0.7258, 0.2001, 0.6679],
        [0.1081, 0.6918, 0.2558],
        [0.5970, 0.9447, 0.8152]])
Tamaño: torch.Size([3, 3])
Tipo de dato: torch.float32
Dispositivo: cpu

Tensor de ceros: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Tamaño: torch.Size([4, 4])
Tipo de dato: torch.float32
Dispositivo: cpu




<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>Ejercicio 2:Operaciones Básicas con Tensores</strong></div>

* Crea dos tensores de tamaño (2, 2) con valores a tu elección.

* Suma los dos tensores.

* Multiplica los dos tensores elemento por elemento.

* Calcula el producto matricial de los dos tensores.





In [13]:
import torch

# Crear tensores 2x2
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Sumar tensores
suma = tensor_a + tensor_b

# Multiplicar elemento por elemento
multiplicacion_elemento = tensor_a * tensor_b

# Producto matricial
producto_matricial = torch.matmul(tensor_a, tensor_b)

# Imprimir resultados
print("Suma:\n", suma)
print("Multiplicación elemento a elemento:\n", multiplicacion_elemento)
print("Producto matricial:\n", producto_matricial)

Suma:
 tensor([[ 6,  8],
        [10, 12]])
Multiplicación elemento a elemento:
 tensor([[ 5, 12],
        [21, 32]])
Producto matricial:
 tensor([[19, 22],
        [43, 50]])




<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>Ejercicio 3: Manipulación de Tensores</strong></div>

* Crea un tensor de tamaño (4, 4) inicializado con números aleatorios.

* Cambia la forma del tensor a (2, 8).

* Concatenar dos tensores de tamaño (2, 2) a lo largo de la dimensión 0.

* Obtén la suma de todos los elementos de un tensor.





In [14]:
import torch

# Tensor aleatorio 4x4
tensor_random = torch.rand(4, 4)

# Cambiar la forma a 2x8
tensor_reshaped = tensor_random.view(2, 8)

# Crear dos tensores 2x2
tensor_x = torch.tensor([[1, 2], [3, 4]])
tensor_y = torch.tensor([[5, 6], [7, 8]])

# Concatenar los tensores a lo largo de la dimensión 0
tensor_concatenado = torch.cat((tensor_x, tensor_y), dim=0)

# Sumar todos los elementos de un tensor
suma_total = torch.sum(tensor_x)

# Imprimir resultados
print("Tensor original 4x4:\n", tensor_random)
print("Tensor cambiado a 2x8:\n", tensor_reshaped)
print("Tensor concatenado a lo largo de la dimensión 0:\n", tensor_concatenado)
print("Suma de todos los elementos en tensor_x:\n", suma_total)


Tensor original 4x4:
 tensor([[0.7772, 0.2678, 0.9198, 0.3535],
        [0.2497, 0.5864, 0.0030, 0.9165],
        [0.0300, 0.6727, 0.9548, 0.5579],
        [0.2797, 0.1662, 0.6853, 0.7344]])
Tensor cambiado a 2x8:
 tensor([[0.7772, 0.2678, 0.9198, 0.3535, 0.2497, 0.5864, 0.0030, 0.9165],
        [0.0300, 0.6727, 0.9548, 0.5579, 0.2797, 0.1662, 0.6853, 0.7344]])
Tensor concatenado a lo largo de la dimensión 0:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Suma de todos los elementos en tensor_x:
 tensor(10)




<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>Ejercicio 5: Extracción de Valores de un Tensor</strong></div>

* Crea un tensor escalar (un solo número).

* Extrae el valor como un escalar de Python usando .item().

* Crea un tensor de múltiples dimensiones y conviértelo en un arreglo NumPy.

* Extrae un valor específico del tensor multidimensional.

In [15]:
import torch

# Crear tensor escalar
tensor_escalar = torch.tensor(42)

# Extraer el valor escalar
valor_escalar = tensor_escalar.item()
print("Valor escalar extraído:", valor_escalar)

# Crear tensor multidimensional
tensor_multi = torch.tensor([[1, 2], [3, 4], [5, 6]])

# Convertir a NumPy
numpy_array = tensor_multi.numpy()
print("Tensor convertido a NumPy:\n", numpy_array)

# Extraer un valor específico del tensor (posición [1, 1])
valor_especifico = tensor_multi[1, 1].item()
print("Valor en posición [1, 1]:", valor_especifico)


Valor escalar extraído: 42
Tensor convertido a NumPy:
 [[1 2]
 [3 4]
 [5 6]]
Valor en posición [1, 1]: 4


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>Ejercicio 4: Indexación y Slicing en Tensores</strong></div>

* Crea un tensor de tamaño (4, 4) con números enteros secuenciales del 1 al 16.

* Extrae el elemento en la fila 2, columna 3.

* Extrae la segunda fila completa.

* Extrae las dos primeras columnas de todas las filas.

* Cambia el valor en la posición (3, 3) a 99.

* Extrae un subtensor que contenga las filas 1 y 2 y las columnas 2 y 3.

* Obtén un tensor que contenga la penúltima columna

In [16]:
import torch

# Crear un tensor de tamaño 4x4 con números del 1 al 16
tensor = torch.arange(1, 17).view(4, 4)

# Imprimir el tensor original
print("Tensor original:\n", tensor)

# 1. Extraer el elemento en la fila 2, columna 3 (recuerda que los índices comienzan desde 0)
elemento = tensor[1, 2]
print("\nElemento en la fila 2, columna 3:", elemento)

# 2. Extraer la segunda fila
segunda_fila = tensor[1, :]
print("\nSegunda fila completa:", segunda_fila)

# 3. Extraer las dos primeras columnas de todas las filas
primeras_columnas = tensor[:, :2]
print("\nDos primeras columnas de todas las filas:\n", primeras_columnas)

# 4. Cambiar el valor en la posición (3, 3) a 99
tensor[2, 2] = 99
print("\nTensor después de cambiar el valor en (3, 3) a 99:\n", tensor)

# 5. Extraer un subtensor con las filas 1 y 2, y las columnas 2, 3
subtensor = tensor[:2, 1:3]
print("\nSubtensor (filas 1 y 2, columnas 2 y 3):\n", subtensor)

# 6. Extraer un subtensor con la penúltima columna
subtensor = tensor[:, -2]
print("\nSubtensor con la penúltima columna:\n", subtensor)


Tensor original:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Elemento en la fila 2, columna 3: tensor(7)

Segunda fila completa: tensor([5, 6, 7, 8])

Dos primeras columnas de todas las filas:
 tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]])

Tensor después de cambiar el valor en (3, 3) a 99:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 99, 12],
        [13, 14, 15, 16]])

Subtensor (filas 1 y 2, columnas 2 y 3):
 tensor([[2, 3],
        [6, 7]])

Subtensor con la penúltima columna:
 tensor([ 3,  7, 99, 15])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>Ejercicio 6: El ejemplo de la convolución</strong></div>

Explicar qué es lo que realmente no ha ido bien en el ejemplo de la convolución y los parches de $2\times 2$. Dar una pista de cómo se podría arreglar usando [permute()](https://docs.pytorch.org/docs/2.14/generated/torch.permute.html).

Lo primero que tenemos que localizar es el fallo. Recordemos el ejemplo que hemos hecho.


In [17]:
x = torch.arange(16).reshape(1, 1, 4, 4)
print(x)
xres = x.reshape(2, 2, 2, 2)
print(xres.shape)
print(xres)

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15]]]])
torch.Size([2, 2, 2, 2])
tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]])


En el que vemos que cada parche no es realmente un parche de la figura porque lo que alberga es una fila completa de píxels. Lo que queremos es que cada parche albergue mitad de una fila y mitad de la siguiente. Es decir, tenemos

$$
\begin{array}{cc}
\text{Patch 1} & \text{Patch 2} \\[2mm]

\begin{array}{|c|c|}
\hline
0 & 1 \\ \hline
2 & 3 \\ \hline
\end{array}
&
\begin{array}{|c|c|}
\hline
4 & 5 \\ \hline
6 & 7 \\ \hline
\end{array}
\\[5mm]

\text{Patch 3} & \text{Patch 4} \\[2mm]

\begin{array}{|c|c|}
\hline
8 & 9 \\ \hline
10 & 11 \\ \hline
\end{array}
&
\begin{array}{|c|c|}
\hline
12 & 13 \\ \hline
14 & 15 \\ \hline
\end{array}

\end{array}$$

y  queremos

$$
\begin{array}{cc}
\text{Patch 1} & \text{Patch 2} \\[2mm]

\begin{array}{|c|c|}
\hline
0 & 1 \\ \hline
4 & 5 \\ \hline
\end{array}
&
\begin{array}{|c|c|}
\hline
2 & 3 \\ \hline
6 & 7 \\ \hline
\end{array}
\\[5mm]

\text{Patch 3} & \text{Patch 4} \\[2mm]

\begin{array}{|c|c|}
\hline
8 & 9 \\ \hline
12 & 13 \\ \hline
\end{array}
&
\begin{array}{|c|c|}
\hline
10 & 11 \\ \hline
14 & 15 \\ \hline
\end{array}

\end{array}$$



Lo que hace `permute()` es recibir una lista con el nuevo orden de dimensiones. Por ejemplo, si nuestro tensor tiene cuatro dimensiones, y le aplicamos `permute(0,4,2,1)` reordenará el tensor para que la dimensión 0 sea la original, la 2 sea la antigua 4, la 3 sea la 2 y la última la 1 original.

Supongamos un ejemplo de un array de tres dimensiones en el que tenemos a todos los alumnos de nuestra asignatura, y para cada alumno un examen y dentro de cada examen una calificación. Si quisiéramos en lugar de acceder por alumno a nuestra estructura, acceder por examen, aplicaríamos un `permute(1,0,2)` a la estructura original y ya lo tendríamos. 

Volviendo a nuestro problema, ¿Qué significa cada una de nuestras cuatro dimensiones?

* Dimensión 0: filas de nuestros parches

* Dimensión 1: filas de nuestro pixels dentro del parche

* Dimensión 2: columnas del parche

* Dimensión 3: columnas de los píxels dentro un parche

Pero yo lo que quiero, por este orden, es acceder primero a fila y columna de los cuatro parches, y luego a fila y columna de los pixels dentro de un parche. Por tanto, ya sé cómo invocar a `permute()`

In [18]:
xresok = xres.permute(0, 2, 1, 3)
print(xresok)


tensor([[[[ 0,  1],
          [ 4,  5]],

         [[ 2,  3],
          [ 6,  7]]],


        [[[ 8,  9],
          [12, 13]],

         [[10, 11],
          [14, 15]]]])
